input {
  beats {
    port => 5044
  }

  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [service] == "nginx" {
    mutate {
      add_tag => ["web", "edge"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    data_stream => "true"
    data_stream_type => "logs"
    data_stream_dataset => "opc"
    data_stream_namespace => "default"
  }

  stdout {
    codec => rubydebug
  }
}
